<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>詳細情報</title>
    </head>
    <body>
        <table class="table table-bordered table-striped">
            <tr>
                <th width="150">
                    アドレス帳ID
                </th>
                <td>
                    {{$record->id}}
                </td>
            </tr>
            <tr>
                <th>
                    役職
                </th>
                <td>
                    {{$record->position}}
                </td>
            </tr>
            <tr>
                <th>
                    名前
                </th>
                <td>
                    <small>({{$record->name_kana}})</small></br>
                    {{$record->name}}
                </td>
            </tr>
            <tr>
                <th>
                    電話帳種別
                </th>
                <td>
                    {{$AddressBookType[$record->type]}}
                </td>
            </tr>
            <tr>
                <th>
                    所属グループ
                </th>
                <td>
                    {{$record->GroupName()}}
                </td>
            </tr>
            <tr>
                <th>
                    電話番号1
                </th>
                <td>
                    {{$record->tel1}}
                </td>
            </tr>
            <tr>
                <th>
                    電話番号2
                </th>
                <td>
                    {{$record->tel2}}
                </td>
            </tr>
            <tr>
                <th>
                    電話番号3
                </th>
                <td>
                    {{$record->tel3}}
                </td>
            </tr>
            <tr>
                <th>
                    メールアドレス
                </th>
                <td>
                    @if($record->email)
                    <a href="mailto:{{$record->email}}">{{$record->email}}</a>
                    @endif
                </td>
            </tr>
            <tr>
                <th>
                    備考
                </th>
                <td>
                    {{$record->comment}}
                </td>
            </tr>
        </table>
    </body>
</html>
